# Generated by Django 4.0.3 on 2022-05-19 12:49

import django.core.validators
from django.db import migrations, models
import teacher.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document',
            field=models.FileField(upload_to=teacher.utils.report_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='report_student',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=teacher.utils.students_report_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='document',
            field=models.FileField(upload_to=teacher.utils.subject_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
