# Generated by Django 3.2.5 on 2022-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
