# Generated by Django 3.2.5 on 2022-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20220221_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='quizzes', to='teacher.Course'),
        ),
    ]
