# Generated by Django 3.2.5 on 2022-02-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_quiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.Course'),
        ),
    ]
