# Generated by Django 3.2.5 on 2022-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20220221_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
