# Generated by Django 3.2.5 on 2022-02-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_alter_answer_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
