# Generated by Django 3.2.5 on 2022-02-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_answer_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='QuestionAnswer',
        ),
    ]
