# Generated by Django 3.2.12 on 2022-02-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_rename_answer_questionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Question Answer'},
        ),
    ]
