# Generated by Django 3.2.12 on 2022-02-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20220223_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizstudent',
            old_name='done_or_not',
            new_name='done',
        ),
    ]
