# Generated by Django 3.2.5 on 2022-02-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_rename_done_or_not_quizstudent_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students',
        ),
        migrations.AlterUniqueTogether(
            name='quizstudent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizstudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizstudent',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizStudent',
        ),
    ]
