# Generated by Django 3.2.12 on 2022-02-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_auto_20220224_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='description_report',
        ),
    ]
