# Generated by Django 3.2.12 on 2022-02-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_rename_description_report_description_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description_report',
            new_name='description',
        ),
    ]
