# Generated by Django 3.2.12 on 2022-02-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_rename_description_report_report_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='description_report',
        ),
    ]
