# Generated by Django 3.2.12 on 2022-03-12 19:32

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default.png', null=True, upload_to=teacher.models.course_directory_path),
        ),
    ]
