# Generated by Django 3.2.12 on 2022-03-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_auto_20220316_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstudent',
            name='final_grade',
        ),
    ]
