# Generated by Django 3.2.12 on 2022-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0035_remove_reportstudent_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstudent',
            name='grade',
            field=models.CharField(blank=True, choices=[('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا')], max_length=200, null=True),
        ),
    ]
