# Generated by Django 3.2.12 on 2022-03-16 18:54

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0037_auto_20220316_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_student',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=teacher.models.students_report_directory_path),
        ),
    ]
