# Generated by Django 3.2.12 on 2022-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0038_report_student_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_student',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='report_student',
            name='grade',
            field=models.CharField(blank=True, choices=[('لم يتم التسليم', 'لم يتم التسليم'), ('لم يتم التقييم', 'لم يتم التقييم'), ('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز')], max_length=200, null=True),
        ),
    ]
