# Generated by Django 3.2.12 on 2022-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='correct',
            field=models.CharField(choices=[('الاختيار الاول', 'الاختيار الاول'), ('الاختيار التانى', 'الاختيار التانى'), ('الاختيار التالت', 'الاختيار التالت'), ('الاختيار الرابع', 'الاختيار الرابع')], max_length=200),
        ),
    ]
