# Generated by Django 3.2.12 on 2022-03-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_questionanswer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
