# Generated by Django 3.2.12 on 2022-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=120)),
                ('desc', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
