# Generated by Django 3.2.12 on 2022-05-13 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import qorb.teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='course_images/default.png', null=True, upload_to=qorb.teacher.models.course_directory_path)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('student', models.ManyToManyField(blank=True, null=True, related_name='student', to='accounts.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_report', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('document', models.FileField(upload_to=qorb.teacher.models.report_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('document', models.FileField(upload_to=qorb.teacher.models.subject_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Report_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to=qorb.teacher.models.students_report_directory_path)),
                ('grade', models.CharField(choices=[('لم يتم التسليم', 'لم يتم التسليم'), ('لم يتم التقييم', 'لم يتم التقييم'), ('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز')], default='لم يتم التسليم', max_length=200)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'report')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='students',
            field=models.ManyToManyField(through='teacher.Report_student', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='report',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
