# Generated by Django 3.2.5 on 2022-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
