# Generated by Django 3.2.5 on 2022-02-21 16:14

from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teacher', '0009_alter_degree_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document',
            field=models.FileField(upload_to=teacher.models.report_directory_path),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(verbose_name='quiz durations in minutes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('course', models.ManyToManyField(blank=True, null=True, to='teacher.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
            ],
        ),
    ]
