# Generated by Django 3.2.5 on 2022-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_alter_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
