# Generated by Django 3.2.12 on 2022-03-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teacher', '0030_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporttudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا')], max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'report')},
            },
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.AddField(
            model_name='report',
            name='students',
            field=models.ManyToManyField(through='teacher.Reporttudent', to='accounts.Student'),
        ),
    ]
