# Generated by Django 3.2.12 on 2022-03-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teacher', '0031_auto_20220316_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporttudent',
            new_name='Reportstudent',
        ),
    ]
