# Generated by Django 3.2.12 on 2022-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0032_rename_reporttudent_reportstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstudent',
            name='degree',
            field=models.CharField(blank=True, choices=[('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا')], max_length=200, null=True),
        ),
    ]
