# Generated by Django 3.2.12 on 2022-03-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teacher', '0036_reportstudent_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('لم يتم التقييم', 'لم يتم التقييم'), ('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا')], max_length=200, null=True)),
                ('done', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'report')},
            },
        ),
        migrations.DeleteModel(
            name='Reportstudent',
        ),
        migrations.AlterField(
            model_name='report',
            name='students',
            field=models.ManyToManyField(through='teacher.Report_student', to='accounts.Student'),
        ),
    ]
