# Generated by Django 3.2.12 on 2022-03-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0043_report_student_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_student',
            name='enrolled_at',
        ),
    ]
