# Generated by Django 3.2.12 on 2022-03-21 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0044_remove_report_student_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_student',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report_student',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
