# Generated by Django 3.2.12 on 2022-03-23 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0045_auto_20220321_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_student',
            name='deadline',
        ),
        migrations.AddField(
            model_name='report',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
