# Generated by Django 3.2.12 on 2022-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0046_auto_20220323_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_student',
            name='grade',
            field=models.CharField(choices=[('لم يتم التسليم', 'لم يتم التسليم'), ('لم يتم التقييم', 'لم يتم التقييم'), ('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز')], default='لم يتم التسليم', max_length=200),
        ),
    ]
